### ISSUE TITLE
test-helper does not read settings.js

### ISSUE THREAD

**Issue by cdlans** [node-red/node-red-node-test-helper#21]
At the moment it is impossible to test a flow which has a function node, which loads a module with a call to `global.get()`. (See the [documentation](https://nodered.org/docs/writing-functions#loading-additional-modules) on loading modules in function nodes.)

Reason is that the test helper doesn't read a `settings.js` file in [`index.js:159`](https://github.com/node-red/node-red-node-test-helper/blob/master/index.js#L159).

**Comment by knolleary** [comment]
I don't think test-helper should be reading a settings file - but it should let you provide a settings object as part of the api.
