### ISSUE TITLE
Return Promise for helper.load

### ISSUE THREAD

**Issue by JbIPS** [node-red/node-red-node-test-helper#42]
Hi,

I noticed that `helper.load` only works with a callback but ultimately [relies on a Promise](https://github.com/node-red/node-red-node-test-helper/blob/master/index.js#L246).

Could you return it instead of forcing a callback and no return value?

I can do the PR if it's OK with you.

**Comment by knolleary** [comment]
A PR would be welcome as long as the callback is still called if provided to maintain the existing behaviour.

**Comment by JbIPS** [comment]
PR is done, let me know if anything's missing.
