### ISSUE TITLE
credentials is undefined

### ISSUE THREAD

**Issue by enorfelt** [node-red/node-red-node-test-helper#47]
How do I use testCredentials?

I supply credentials like this in my test:

`var credentials = {`
`     userid: "username",`
`     apikey: "password",`
`   };`
`   helper.load(bfApiReq, flow, credentials, function () {`

Then in my node `this.credentials.userid` is undefined.

**Comment by enorfelt** [comment]
I think I figured it out. You have do define witch flow the credentials belong to.
Like this:
```javascript
var credentials = {
      n1: {
        userid: "username",
        apikey: "password",
      },
    };
```

**Comment by javis86** [comment]
This needs to be in docs!
