### ISSUE TITLE
Test Server doesn't support nodes built with ES6 Classes

### ISSUE THREAD

**Issue by AllanOricil** [node-red/node-red-node-test-helper#80]
Node is registered without a problem (apparently, since no exception is throw)

<img width="1249" alt="image" src="https://github.com/user-attachments/assets/8850000b-62a2-4656-bc3a-514d38189e60">

However, `n1` is null, as you can see in the "Debugger's watcher", during assertion in the callback

<img width="848" alt="image" src="https://github.com/user-attachments/assets/59765f90-799a-47a5-9d02-5c9dd377ebde">

Registration works fine since this built in helper assertion at lne 322 succeeds

<img width="781" alt="image" src="https://github.com/user-attachments/assets/9a77ea60-0ad5-4a4f-b551-d08727346597">

I noticed that my node's constructor is never called in this test server. In a production server, a node built with a ES6 Class works without a problem, and its constructor is called.

<img width="641" alt="image" src="https://github.com/user-attachments/assets/278ad75b-a3f8-4277-bdd0-5827d82a4efe">

My guess is that `RED.nodes.registerType` works differently in this test server, since my node's constructor is never called.

Unit Test

```js
it("test node1", () => {
    const flow = [
      {
        id: "n1",
        type: "node-1",
        name: "node-1",
        z: "flow",
      },
    ];

    axios.get.mockResolvedValue({
      data: {},
    });

    helper.load(
      async function (RED) {
        const NodeRedNodeMixin = createNodeRedNodeMixin(RED);
        const _Node1 = await NodeRedNodeMixin(Node1, "node-1");
        RED.nodes.registerType(
          "node-1",
          _Node1,
          _Node1.registrationProperties()
        );
      },
      flow,
      function () {
        const n1 = helper.getNode("n1");
        n1.should.have.property();
      }
    );
  });
````

**Comment by knolleary** [comment]
Do you have an example node this is failing with? I don't have any using ES6 classes - will be helpful if you have something we create reproduce this with.

**Comment by AllanOricil** [comment]
> Do you have an example node this is failing with? I don't have any using ES6 classes - will be helpful if you have something we create reproduce this with.

I will share an example soon

**Comment by AllanOricil** [comment]
# Steps to Reproduce

1. clone git@github.com:AllanOricil/nrg-template.git
2. checkout `vitest` branch
3. npm run install
4. update `node-red-node-test-helper` with the changes from this [PR](https://github.com/node-red/node-red-node-test-helper/pull/81). You can open `./node_modules/node-red-node-test-helper/index.js` and paste those changes there to ease the setup, instead of linking the package.
5. npm run test
6. verify that `n1` is null and the following error is throw

<img width="1190" alt="image" src="https://github.com/user-attachments/assets/74c58e0b-70a2-4415-a6c0-ede6856eefba">

**Comment by knolleary** [comment]
Thanks for that - can reproduce and am digging in to the root cause.

It is a bit strange. I can see both the `helper` and `node-1` types are being registered. But when the runtime then comes to start the flows and asks the registry for the constructor of the `node-1` type, the registry is empty - it doesn't know about either the `helper` or `node-1` types. It is almost as if its an entirely different registry.

Can't yet figure out if this is ES6 classes related, or something else with how nrg is wrapping up the nodes differently to how we've done it previously... or something else entirely.

**Comment by knolleary** [comment]
Found it. The `afterEach` is triggering and clearing the registry before the test has finished running.

`helper.load` calls the callback function with the actual test logic in asynchronously - however vitest doesn't know this and the test function is returning before helper.load has finished. vitest assumes the test has finished and moves on.

If vitest doesn't like `done` functions in its test definitions, then `helper.load` will need to be made async as well so you can await it.

**Comment by AllanOricil** [comment]
Right. I will make the other method async. Thanks

**Comment by AllanOricil** [comment]
@knolleary 
https://github.com/node-red/node-red-node-test-helper/pull/82
